## 期约与异步函数

### 异步编程

#### 同步与异步

同步行为对应内存中顺序执行的处理器指令。每条指令都会严格按照它们出现的顺序来执行，而每条指令执行后也能立即获得存储在系统本地（如寄存器或系统内存）的信息

所有指令都是在单个线程中按顺序执行的

异步行为类似于系统中断，即当前进程外部的实体可以触发代码执行。异步操作经常是必要的，因为强制进程等待一个长时间的操作通常是不可行的, 如果代码要访问一些高延迟的资源，比如向远程服务器发送请求并等待响应，那么就会出现长时间的等待

#### 以往的异步编程模式

在之前: 支持定义回调函数来表名异步操作完成

```js
function double(value) {
  setTimeout(() => setTimeout(console.log, 0, value * 2), 1000)
}
double(3)
```

1. 异步返回值

```js
function double(value, callback) {
  setTimeout(() => callback(value * 2), 1000)
}
double(3, (x) => console.log(`I was given: ${x}`))
// I was given: 6（大约 1000 毫秒之后
```

2. 失败处理

异步操作的失败处理在回调模型中也要考虑, 成功回调, 失败回调

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== "number") {
        throw "Must provide number as first argument"
      }
      success(2 * value)
    } catch (e) {
      failure(e)
    }
  }, 1000)
}
const successCallback = (x) => console.log(`Success: ${x}`)
const failureCallback = (e) => console.log(`Failure: ${e}`)
double(3, successCallback, failureCallback)
double("b", successCallback, failureCallback)
// Success: 6（大约 1000 毫秒之后）
// Failure: Must provide number as first argument（大约 1000 毫秒之后
```

3. 嵌套回调

如果异步返值又依赖另一个异步返回值，那么回调的情况还会进一步变复杂

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== "number") {
        throw "Must provide number as first argument"
      }
      success(2 * value)
    } catch (e) {
      failure(e)
    }
  }, 1000)
}
const successCallback = (x) => {
  double(x, (y) => console.log(`Success: ${y}`))
}
const failureCallback = (e) => console.log(`Failure: ${e}`)
double(3, successCallback, failureCallback)
// Success: 12（大约 1000 毫秒之后）
```

### Promise

#### promise 基础

ES6 新增了引用类型 `Promise`, 可以通过 `new`操作符来实例化

1. promise 状态机

在把一个 promise 实例传给 console.log() 时, 控制台输出表明实例处于 `待定 pending` 状态

- `pending` 待定
- `fulfilled` 兑现/解决
- `rejected` 拒绝

待定是 promise 的最初始状态, 无论落定为那种状态, 状态不再改变.

2. 解决值. 拒绝理由及 promise 用例

promise 两大作用: 首先表示一个异步操作. promise 封装的异步操作会实际生成某个值

3. 通过执行函数控制 promise 状态

```js
let p1 = new Promise((reslove, reject) => reslove())
setTimeout(console.log, 0, p1)

let p2 = new Promise((reslove, reject) => reject())
setTimeout(console.log, 0, p2) // Promise <rejected
```

4. `promise.resolve()`

`promise`并非一开始就必须处于待定状态, 然后通过执行器函数才能转换为落定状态

`Promise.resolve()`静态方法，可以实例化一个解决的 promise

```js
// 实际上是一样的
let p1 = new Promise((resolve, reject) => resolve())
let p2 = Promise.resolve()

setTimeout(console.log, 0, Promise.resolve())
// Promise <resolved>: undefined
setTimeout(console.log, 0, Promise.resolve(3))
// Promise <resolved>: 3
// 多余的参数会忽略
setTimeout(console.log, 0, Promise.resolve(4, 5, 6))
// Promise <resolved>: 4
```

对于这个静态方法来说, 如果传入的参数本身是一个 `promise`, 那它的行为就类似于一个空包装. 因此, `Promise.reslove()` 可以说是一个幂等方法

```js
let p = Promise.reslove(7)
setTimeout(console.log, 0, p === Promise.resolve(p))
setTimeout(console.log, 0, p === Promise.resolve(Promise.resolve(p)))
// true

// 这个幂等性会保留传入 promise 的状态
let p = new Promise(() => {})
setTimeout(console.log, 0, p) // Promise <pending>
setTimeout(console.log, 0, Promise.resolve(p)) // Promise <pending>
setTimeout(console.log, 0, p === Promise.resolve(p)) // true
```

这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约

```js
let p = Promise.resolve(new Error("foo"))
setTimeout(console.log, 0, p)
// Promise <resolved>: Error: foo
```

5. `Promise.reject()`

`Promise.reject()`会实例化一个拒绝的期约并抛出一个异步错误（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）

```js
let p1 = new Promise((resolve, reject) => reject())
let p2 = Promise.reject()

let p = Promise.reject(3)
setTimeout(console.log, 0, p) // Promise <rejected>: 3
p.then(null, (e) => setTimeout(console.log, 0, e)) // 3

// 如果给它传一个 promise 对象，则这个 promise 会成为它返回的拒绝期约的理由
setTimeout(console.log, 0, Promise.reject(Promise.resolve()))
// Promise <rejected>: Promise <resolved>
```

### Promise 的实例方法

promise 的实例方法是链接外部同步代码的桥梁, 这些方法可以访问异步操作返回的数据，处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码

1. 实现 `Thenable` 接口

在 ES 暴露的异步结构中, 任何对象都有一个 `then()` 方法.

```js
// 实现Thenable最简单的类
class MyThenable {
  then() {}
}
```

2. `Promise.prototype.then()`

`Promise.prototype.then()`是为 promise 实例添加处理程序的主要方法。这个 `then()`方法接收最多两个参数：`onResolved` 处理程序和 `onRejected` 处理程序。这两个参数都是可选的，如果提供的话，则会在 promise 分别进入“兑现”和“拒绝”状态时执行

```js
let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000))
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000))

p1.then(
  () => onResloved("p1"),
  () => onRejected("p1")
)

let p1 = Promise.resolve("foo")
// 若调用 then() 时不传处理程序, 则原样向后传
let p2 = p1.then()

setTimeout(console.log, 0, p2) // Promise <resolved>: foo

// 这些都一样
let p3 = p1.then(() => undefined)
let p4 = p1.then(() => {})
let p5 = p1.then(() => Promise.resolve())

setTimeout(console.log, 0, p3) // Promise <resolved>: undefined
setTimeout(console.log, 0, p4) // Promise <resolved>: undefined
setTimeout(console.log, 0, p5) // Promise <resolved>: undefined

// 有显式的返回值, 则 Promise.resolve() 会包装这个值
let p6 = p1.then(() => "bar")
let p7 = p1.then(() => Promise.resolve("bar"))

setTimeout(console.log, 0, p6) // Promise <resolved>: bar
setTimeout(console.log, 0, p7) // Promise <resolved>: bar

// Promise.resolve()保留返回的期约
let p8 = p1.then(() => new Promise(() => {}))
let p9 = p1.then(() => Promise.reject())
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p8) // Promise <pending>
setTimeout(console.log, 0, p9) // Promise <rejected>: undefined

// 返回错误值不会触发上面的拒绝行为，而会把错误对象包装在一个解决的期约中
let p10 = p1.then(() => {
  throw "baz"
})
// Uncaught (in promise) baz
setTimeout(console.log, 0, p10) // Promise <rejected> baz
```

3. `Promise.prototype.catch()`

`Promise.prototype.catch()`方法用于给 promise 添加拒绝处理程序. 这个方法只接受一个参数: `onRejected`处理程序. 事实上, 这个方法是一个语法糖. 相当于调用 `Promise.prototype.then(null, onRejected)`

```js
let p = Promise.reject()
let onRejected = function (e) {
  setTimeout(console.log, 0, "rejected")
}
// 这两种添加拒绝处理程序的方式是一样的：
p.then(null, onRejected) // rejected
p.catch(onRejected) // rejected
```

`Promise.prototype.catch()`返回一个新的 `promise` 实例

```js
let p1 = new Promise(() => {})
let p2 = p1.catch()
setTimeout(console.log, 0, p1) // Promise <pending>
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(console.log, 0, p1 === p2) // false
```

4. `Promise.prototype.finally()`